#!/bin/bash

tdbquery \
  --verbose \
  --time \
  --loc /bigdata/semantic/tdb/music-2021-03-05 \
  --explain \
  --optimize=on \
  --results=CSV \
  --base="http://file.org#" \
  --file=04.count-mp3-vorbis.rq > 04.count-mp3-vorbis.rq.csv

