#!/bin/bash

cdate=$(date +"%Y-%m-%d")

rm -f ./bin/*

mvn clean package && \
 mvn install dependency:copy-dependencies && \
 cp -f target/meta-collector-*.jar ./bin && \
 cp -f target/dependency/* ./bin

echo "Compillation status = $?"

java -jar bin/meta-collector-*.jar \
  /storage/music \
  /bigdata/semantic/music-$cdate.ttl \
  /bigdata/semantic/music-$cdate.xml \
  /bigdata/semantic/tdb/music-$cdate

